
＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:28:30,811                                   
【线程编号】[21]                                   
【执行时间】[4911]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错的类】LessSharp.WebApi.Controllers.TestController 属性[(null)]                                   
【错误描述】test                                   
【错误详情】
System.Exception: haha

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:30:54,933                                   
【线程编号】[20]                                   
【执行时间】[11819]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】haha                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16() in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:36:23,920                                   
【线程编号】[21]                                   
【执行时间】[4751]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】haha                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16() in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:40:34,424                                   
【线程编号】[21]                                   
【执行时间】[6086]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【EventId】eventId                                   
【EventId】eventid                                   
【EventId】{log4net:HostName=CAIJT-X220, log4net:UserName=NOT AVAILABLE, log4net:Identity=NOT AVAILABLE, RequestId=8000063c-0002-ff00-b63f-84710c7967bb, TraceId=88bcd8dd-456ad4ca34961869, ParentId=, SpanId=|88bcd8dd-456ad4ca34961869., RequestPath=/api/Test/Test16}                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】haha                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16() in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:41:57,296                                   
【线程编号】[21]                                   
【执行时间】[6727]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【EventId】eventId                                   
【EventId】eventid                                   
【EventId】{RequestPath=/api/Test/Test16, ParentId=, log4net:Identity=NOT AVAILABLE, log4net:UserName=NOT AVAILABLE, RequestId=8000063e-0002-ff00-b63f-84710c7967bb, TraceId=72db2cf6-4c7b395e51402a7a, log4net:HostName=CAIJT-X220, SpanId=|72db2cf6-4c7b395e51402a7a.}                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】ea49ec89-b703-4118-a81f-fab918a619ff                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16() in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:44:12,874                                   
【线程编号】[22]                                   
【执行时间】[16568]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【EventId】eventId                                   
【EventId】eventid                                   
【EventId】{RequestPath=/api/Test/Test16, RequestId=800005a3-0001-fa00-b63f-84710c7967bb, TraceId=f3079a5a-4f5de7642e2fb50e, SpanId=|f3079a5a-4f5de7642e2fb50e., ParentId=, log4net:HostName=CAIJT-X220, log4net:Identity=NOT AVAILABLE, log4net:UserName=NOT AVAILABLE}                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】5f6a52b4-c9a8-4ac0-b7d2-4f52bd92d39e                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16(String a) in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:44:23,097                                   
【线程编号】[19]                                   
【执行时间】[26791]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【EventId】eventId                                   
【EventId】eventid                                   
【EventId】{RequestPath=/api/Test/Test16, RequestId=80000618-0001-fb00-b63f-84710c7967bb, TraceId=f3079a5e-4f5de7642e2fb50e, SpanId=|f3079a5e-4f5de7642e2fb50e., ParentId=, log4net:HostName=CAIJT-X220, log4net:Identity=NOT AVAILABLE, log4net:UserName=NOT AVAILABLE}                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】72d457b4-7982-45b6-9b03-c943f662786a                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16(String a) in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:50:34,371                                   
【线程编号】[21]                                   
【执行时间】[5991]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【EventId】NOT AVAILABLEspnet-request                                   
【EventId】?                                   
【EventId】?                                   
【EventId】{log4net:HostName=CAIJT-X220, log4net:Identity=NOT AVAILABLE, RequestPath=/api/Test/Test16, ParentId=, RequestId=8000061a-0001-fb00-b63f-84710c7967bb, SpanId=|7539e96a-46b67ec85a4311b3., TraceId=7539e96a-46b67ec85a4311b3, log4net:UserName=NOT AVAILABLE}                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】8c36eab7-5920-47da-8d11-403ad8f06c38                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16(String a) in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:55:37,511                                   
【线程编号】[18]                                   
【执行时间】[12503]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【EventId】NOT AVAILABLEspnet-request                                   
【EventId】?                                   
【EventId】?                                   
【EventId】{TraceId=696a83e6-45c2ac85dd1b16cc, ParentId=, log4net:HostName=CAIJT-X220, SpanId=|696a83e6-45c2ac85dd1b16cc., RequestId=80000640-0002-ff00-b63f-84710c7967bb, log4net:Identity=NOT AVAILABLE, log4net:UserName=NOT AVAILABLE, RequestPath=/api/Test/Test16}                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】d0b1ddd1-53d7-4f23-b57d-27158e9fe2c3                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16(String a) in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:57:34,834                                   
【线程编号】[21]                                   
【执行时间】[5073]毫秒                                   
【出错文件】?                                   
【出错行号】?                                   
【出错类名】?                                   
【EventId】NOT AVAILABLEspnet-request                                   
【EventId】?                                   
【EventId】event                                   
【EventId】{SpanId=|5de4b25c-429b898c681152a1., log4net:HostName=CAIJT-X220, RequestPath=/api/Test/Test16, ParentId=, RequestId=8000065a-0000-fd00-b63f-84710c7967bb, log4net:UserName=NOT AVAILABLE, log4net:Identity=NOT AVAILABLE, TraceId=5de4b25c-429b898c681152a1}                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController] 属性[(null)]                                   
【错误描述】4f54b5ac-22fb-4d15-935c-caf9e832ef7f                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16(String a) in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 21:59:27,189                                   
【线程编号】[23]                                   
【执行时间】[7570]毫秒                                   
【出错的类】/api/Test/Test16[LessSharp.WebApi.Controllers.TestController]                                   
【错误描述】haha[50032092-e9f2-4907-938f-332f6ca0805a]                                   
【错误详情】
System.Exception: haha
   at LessSharp.WebApi.Controllers.TestController.Test16(String a) in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\TestController.cs:line 203
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2020-08-28 22:03:28,542                                   
【线程编号】[19]                                   
【执行时间】[32924]毫秒                                   
【出错的类】/Auth/Login[LessSharp.Service.AuthService+<GetTokenByLoginAsync>d__7]                                   
【错误描述】123[5163a2e9-a510-4b76-992f-2e027081dc64]                                   
【错误详情】
System.Exception: 123
   at LessSharp.Service.AuthService.GetTokenByLoginAsync(LoginDto loginDto) in E:\dev\LessSharp3\LessSharp.Service\Common\AuthService.cs:line 52
   at LessSharp.WebApi.Controllers.AuthController.Login(LoginDto loginDto) in E:\dev\LessSharp3\LessSharp.WebApi\Controllers\Common\AuthController.cs:line 40
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at LessSharp.WebApi.Middlewares.ApiExceptionMiddleware.InvokeAsync(HttpContext context, ILoggerFactory loggerFactory) in E:\dev\LessSharp3\LessSharp.WebApi\Middlewares\ApiExceptionMiddleware.cs:line 24
